### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-js-localstorage-wMUDce#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193-kapstpq2uw6ovwmudce.surge.sh/) and meets the following criteria:

- [x] Includes a button that when clicked, will toggle the website between day and night themes
- [x] When a user changes the theme, their choice is remembered in `localStorage`
- [x] The class on the `body` element is always up-to-date with the current theme (either `day-theme` or `night-theme`) -- you can use `document.body.setAttribute('class', 'some-class-name')` to set the class on the `body`
- [x] When the body has the class `day-theme`, the background of the website is light-colored, with a darker color for the text
- [x] When the body has the class `night-theme`, the background of the website is a very dark color, with a lighter color for the text
- [x] Somewhere on the page, the user is told how many times they've visited the website (starting with `1` the first time)

**Comment by stuartpearman** [comment]
Hey Kyle, this looks really nice! There are a couple things I'd take another look at:

The night theme isn't saving properly. It looks like you've setup a function to change the theme, but not one to set it when the page loads. You'll need to do this to be able to keep the last theme used.

Your `changeTheme` function could also be simplified a bit. You can make the style changes to the button in your CSS by using `.night-theme button { ... }` or `.day-theme button { ... }`. And instead of checking `window.localStorage.getItem('storedTheme') === 'day'` in your if statement, I would use the variable that you setup earlier `storedTheme`. You should only have to `get` items from local storage once, when you load the page for the first time.

Let me know if you have any questions :+1:

**Comment by harr1193** [comment]
Fixed it so it loads the last theme on load. I tried multiple ways, but I couldn't change the button to change classes on click without the button onclick() function only working one time.

**Comment by harr1193** [comment]
@stuartpearman Looking at it again actually, using a click eventlistener instead of the onclick() function on the button solved that problem with swapping classes and the button not working.

**Comment by stuartpearman** [comment]
Looks much better Kyle! :shipit:
